### ISSUE TITLE
chown: changing ownership of '/var/lib/mysql/': Operation not permitted

### ISSUE THREAD

**Issue by laeeq80** [docker-library/mariadb#149]
I am using mariadb:10.2.12 docker image and want to deploy on openshift origin. I get following error on openshift origin. Works perfectly on local. Is their a way to get around for this issue or I would need to built a custom image of mariadb? I am running as non-root. Following is my docker file.

> FROM mariadb:10.2.12
> 
> ENV MYSQL_DATABASE="db_profile"
> 
> COPY ./my.cnf /etc/mysql/my.cnf
> COPY ./db_profile.sql /docker-entrypoint-initdb.d/
> 
> RUN adduser mysql root
> 
> USER mysql
> 
> EXPOSE 3306

Error:

> Initializing database
> chown: changing ownership of '/var/lib/mysql/': Operation not permitted
> Cannot change ownership of the database directories to the 'mysql'
> user.  Check that you have the necessary permissions and try again.

**Comment by yosifkit** [comment]
The `chown` error you are seeing must be coming from `mysql_install_db`.  It is probably detecting that the directory mounted at `/var/lib/mysql` is not owned by `mysql` and trying to fix that (which doesn't work because it is not root).

https://github.com/docker-library/mariadb/blob/a1f61de0bb84ed1b4a482361c6aa8b8f4398f5cc/10.2/docker-entrypoint.sh#L90-L91


In the default setup of the image we start the container as root, automatically fix volume permissions, and then step down to the `mysql` user to finish setup and run `mysqld`.

https://github.com/docker-library/mariadb/blob/a1f61de0bb84ed1b4a482361c6aa8b8f4398f5cc/10.2/docker-entrypoint.sh#L66-L72

Since you are starting the container as non-root (which is a valid and supported use case since https://github.com/docker-library/mariadb/pull/59), you are responsible for ensuring that the volume has correct permissions for the user that you are running as.

Since this seems more like a problem with your openshift configuration and not a problem with the image, I'll close the issue.

In the future, it'd be better to post questions like this in [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).

**Comment by laeeq80** [comment]
Once the Volume is set, chmod/chown does not take effect. [link](https://stackoverflow.com/questions/26145351/why-doesnt-chown-work-in-dockerfile)

**Comment by tianon** [comment]
The "chown" at container _runtime_ will, though.  Also, when you bring your
own volume, you need to make sure the permissions of that storage are
appropriate.

**Comment by lingxiankong** [comment]
I met with the same issue, does MariaDB docker image supports to be running by specifying `--user` like MySQL image?
