### ISSUE TITLE
whats the username/password of mysql -beginner in docker-

### ISSUE THREAD

**Issue by jcdelarosa7** [docker-library/mariadb#167]
done installing and running the container but cant seem to login with the root account in mysql

**Comment by wglambert** [comment]
It's the password you gave as an environment variable `-e MYSQL_ROOT_PASSWORD=my_password`. If you were to run the image without specifying that it would fail with an error informing you it's required.

So to connect using `mysql` command you would need to also use the `-p` parameter like `mysql -ppass`, if you want a different user then you could use their respective environment variables for passing that information in `docker run`.

Given that the issue is more of a usability question, it would be more suited for [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
