### ISSUE TITLE
Bugzilla requires version 5.6.12 or later of MySQL

### ISSUE THREAD

**Issue by kaihendry** [docker-library/mariadb#174]
With **mariadb:latest** it would appear version strings look like `v5.5.5-10.3.7-MariaDB-1:10.3.7+maria~jessie`.

Bugzilla is looking for something over 5.5 by the looks of things and chokes on this string. I am not sure who is to blame here, so I have filed a bug https://bugzilla.mozilla.org/show_bug.cgi?id=1467006

How should we please move forward here?

**Comment by yosifkit** [comment]
I would assume that it is a failing of Bugzilla to parse MariaDB's version string correctly. That does seem like a ridiculous version string, but I doubt MariaDB had suddenly changed it recently. Where does it come from? When I run the image I don't see that version:

```console
$ docker run -it --rm mariadb:10.3 --version
mysqld  Ver 10.3.7-MariaDB-1:10.3.7+maria~jessie for debian-linux-gnu on x86_64 (mariadb.org binary distribution)
$ docker run -it --rm mariadb:10.3 mysql --version
mysql  Ver 15.1 Distrib 10.3.7-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2
```

There is not anything that I see to change in the image that would fix this. If the same problem exists when installing MariaDB from a third party (like [Debian's packages](https://packages.debian.org/stretch/mariadb-server-10.1)) then it is probably Bugzilla's fault. Otherwise, it would probably how MariaDB packages it in their repo and would need to be taken up with them:

https://github.com/docker-library/mariadb/blob/4eb0a4a25e178260aeb65285d75cb777f009f932/10.3/Dockerfile#L78

**Comment by wglambert** [comment]
Closing since this appears to be an upstream issue and not something we would change the image for
