### ISSUE TITLE
Performing a CMD command causes Mariadb container to stop

### ISSUE THREAD

**Issue by Febin-kg** [docker-library/mariadb#193]
This is my Dockerfile

```
FROM mariadb
COPY . /usr/src/app
WORKDIR /usr/src/app
# I will be performing a phpmyadmin installation in this script
RUN setup.sh
CMD service mysql start && service apache2 start
```

The container waits for about 20 seconds for mysql service to start and it eventually exits.

This is the only log message I have

> Starting MariaDB database server: mysqld . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . failed!

When I manually exec into the container within 20 seconds and perform a service mysql status, this is the output I have

> [info] MariaDB is stopped..

Any thoughts on how I could manually start the services through CMD ?

**Comment by tanji** [comment]
No offense but you're doing it wrong, you are basically superseding the start logic of MariaDB containers with yours, bypassing several critical components in the process.
The basic principle of docker containerization is that each container should handle one main process (that's not exactly true IRL because you can find containers running multiple processes but that's out of the scope of this discussion).
Enough said, if you want to link phpmyadmin with mariadb, you should start a mariadb container, then a php/apache2 container, for example `7.2-apache-stretch` in https://hub.docker.com/_/php/, and do your phpmyadmin installation in that second container.

**Comment by wglambert** [comment]
Tanji explained it aptly

If you have further questions you should ask [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). As these repositories are for issues with the image and not necessarily for questions of usability

**Comment by Febin-kg** [comment]
I'm running phpmyadmin in a separate container. Thank you.
Apologies for putting it up here. I'd posted the same on Stackoverflow but never got any appropriate response.
