### ISSUE TITLE
user configuration is broken

### ISSUE THREAD

**Issue by igor47** [docker-library/mariadb#214]
i attempted to bring up a container with `RANDOM_ROOT_PASSWORD` and then specified my own username and password in `MYSQL_USER` and `MYSQL_PASSWORD` env vars. alas, when the DB came up, my user didn't have permissions on any db, and so was useless.

i see that in the entrypoint script (https://github.com/docker-library/mariadb/blob/master/10.3/docker-entrypoint.sh#L166) we only ever run `GRANT` for the `MYSQL_USER` if a DB is specified, so i attempted to hack around the issue by specifying `information_schema` as the `MYSQL_DATABASE`. unfortunately, this doesn't work either. by the time those grants run, the root password has already been set, and so the grants fail with `Access denied for user 'root'@'localhost' to database 'information_schema'`

i'm not sure what the intent of the `MYSQL_USER` is, but it's useless without grants. a fix should always grant permissions to that user, even without a db specified, and it should do it possibly before setting the root password.

**Comment by wglambert** [comment]
https://github.com/docker-library/docs/tree/master/mariadb#mysql_user-mysql_password
>This user will be granted superuser permissions (see above) for the database specified by the MYSQL_DATABASE variable.

**Comment by wglambert** [comment]
Going to close since this seems resolved

If you have further questions you could also try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker).
