### ISSUE TITLE
Using a custom MySQL configuration file?

### ISSUE THREAD

**Issue by schafdog** [docker-library/mariadb#216]
I am trying to get a custom configuration into /etc/mysql/conf.d but I cannot get it to work. 

I am following the description on https://hub.docker.com/_/mariadb/ but this does not seem to work. 

`docker run --name mariadb -v /root/docker/mariadb/conf.d:/etc/mysql/conf.d -p 3306:3306 mariadb:latest`

But the custom files does not show up.

Is there a new way of doing this?

**Comment by wglambert** [comment]
```console
$ ls conf.d/
file

$ docker run -dit --rm -v "$PWD"/conf.d:/etc/mysql/conf.d --name mariadb mariadb bash
1a31b9e863cc40e2a45202b46f48d8a6e29c48084efc5692fb56fdfb1069d007

$ docker exec mariadb ls /etc/mysql/conf.d
file
```

Since this issue isn't reproducible I'm going to close, if you have further questions you should ask [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). As these repositories are for issues with the image and not necessarily for questions of usability
