### ISSUE TITLE
Integration for automysqlbackup?

### ISSUE THREAD

**Issue by RogerSik** [docker-library/mariadb#221]
Is there a way to easily integrate / enable automysqlbackup into mariadb docker image? Missing it and it was a conformtable way for achieving easily mysql dumps with compression and rotation. Is also in Ubuntu / Debian repository and doens't havem any dependencies. 

https://sourceforge.net/projects/automysqlbackup/

**Comment by wglambert** [comment]
Looks like there's a user input prompt when installing it, so I don't know how you would automate that from a Dockerfile, but if you find a way then this is what your Dockerfile would be

```Dockerfile
FROM mariadb:10.4
RUN apt update && apt install -y --no-install-recommends automysqlbackup
```

You could also try asking [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://blog.docker.com/2016/11/introducing-docker-community-directory-docker-community-slack/), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repositories are for issues with the image and not necessarily for questions of usability

**Comment by RogerSik** [comment]
Thanks @wglambert  for your response.

Got it now with a Dockerfile and following code:
```
FROM mariadb:10.3

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update && \
    apt-get install -y --no-install-recommends automysqlbackup
```
