### ISSUE TITLE
Remove EOL version 5.5/trusty and 10.0

### ISSUE THREAD

**Issue by J0WI** [docker-library/mariadb#239]
https://mariadb.com/kb/en/library/mariadb-5564-release-notes/
https://mariadb.com/kb/en/library/mariadb-10038-release-notes/
https://mariadb.com/kb/en/library/deprecation-policy/

**Comment by tianon** [comment]
Hmm, according to https://mariadb.com/kb/en/library/changes-improvements-in-mariadb-55/ 5.5 in general is supposed to be supported until April 2020, so maybe we need to switch to a newer (still supported) distribution?  http://ftp.osuosl.org/pub/mariadb/repo/5.5/ubuntu/dists/ does not look promising. :disappointed:

10.0 on the other hand does appear to be completely deprecated, so that's an easy removal :+1: (https://mariadb.com/kb/en/library/changes-improvements-in-mariadb-100/)
