### ISSUE TITLE
Galera + MaxScale  have some problems

### ISSUE THREAD

**Issue by ybwin** [docker-library/mariadb#244]
mariadb is normal  
but maxscale  There are some problems
![image](https://user-images.githubusercontent.com/31563989/57963842-3cc56680-795d-11e9-8088-b61fc647f55c.png)
Any help will be appreciated.

**Comment by wglambert** [comment]
Can you give all the commands you ran and any relevant contextual information or files for reproducing the issue

**Comment by ybwin** [comment]
@wglambert think you for receive your help
Runtime environment is k8s + docker + ceph
There are some phenomena：io is high
io Will be affect maxscale error？

**Comment by wglambert** [comment]
Yeah I think you'd want to ask for help over at [the Docker Community Forums](https://forums.docker.com/), [the Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker)

Without a way to reproduce your error I don't think your issue is pertaining to the `mariadb` image specifically but seems like maybe a configuration issue with Kubernetes or Ceph. If you get a minimal reproducer for your issue and find that there's an error in the way we package Mariadb then it we could probe further
