### ISSUE TITLE
Help on persistence data on Mariadb/Docker

### ISSUE THREAD

**Issue by Roentgine** [docker-library/mariadb#259]
What must be taken into account to persist data in mariadb?, I have a bind volume to a local dir and writing the tables to it works and stores on this vol, but when the docker restart an error displays on trying to reach the tables again: ERROR 1932 table(s) doesn´t exist in engine.

**Comment by wglambert** [comment]
We have a section in the docs about persisting/storing data with this image https://github.com/docker-library/docs/tree/master/mariadb#where-to-store-data

Are you mounting the volume to `/var/lib/mysql`, and are you using mac or windows?

**Comment by Roentgine** [comment]
Thanks for the reply!, i'm using windows 10 with docker desktop, i have to clarify that the mariadb docker image is a custom built from a dockerfile, and i don't have permission to modify it, the only thing was to make it persist, at the begining i start to mounting it to the /var/lib/mysql path, but the image fails to run, so i mount it direct into the work database folder, and all the tables created for it are saved but this persist only when docker still running, when restarting, the tables files are there but it can't be reachable even from the internal cli of the docker, is this a persistence tablespace problem? what i have to consider so i can fix it?

**Comment by wglambert** [comment]
It really depends on what the `docker logs` errors say, whether it's permissions or if it's something to do with already existing data being mounted to the image

But there's a specific repo for issues with Docker Desktop https://github.com/docker/for-win/issues?q=is%3Aissue+mariadb+is%3Aclosed

So I'm going to close since this isn't an error with the image, you could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker)

**Comment by Roentgine** [comment]
thanks!
