### ISSUE TITLE
ERROR 2005 (HY000): Unknown MySQL server host 'db' (2)  Waiting for mysql. This may take few more seconds ...

### ISSUE THREAD

**Issue by shankha-das** [docker-library/mariadb#294]
![Screenshot from 2020-04-08 11-26-25](https://user-images.githubusercontent.com/52560419/78749420-d63da280-798b-11ea-81c0-aa07c8505657.png)
While starting the server getting the error. This setup is based on docker. After running the environment file facing the issue.

**Comment by wglambert** [comment]
Can you post your docker-compose.yml file or all the commands you ran and any relevant contextual information or files for reproducing the issue

You could also try asking over at the [Docker Community Forums](https://forums.docker.com/), [Docker Community Slack](https://dockr.ly/slack), or [Stack Overflow](https://stackoverflow.com/search?tab=newest&q=docker). Since these repos aren't really a user-help forum

**Comment by shankha-das** [comment]
`version: '2'
services:
  api:
    build:
      context: .
    ports:
      - "80:80"
    links:
      - db
      - redis
      - go
    depends_on:
      - db
  resqueue:
    build:
      context: .
    links:
      - redis
    command: cron v1 worker start
    environment:
      COUNT: ${WORKERS_COUNT}
      QUEUE: ${TASK_QUEUE}
  go:
    build:
      context: ./services/goApi/.
    ports:
      - "1323:1323"
    links:
      - db
      - redis
  carrier:
    build:
      context: ./services/carrier/.
    ports:
      - "8090:80"
    links:
      - db
      - redis
      - api
  db:
    image: mysql:5.7
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${PHINX_MYSQL_PWD}
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    image: redis:latest
    command: redis-server --appendonly yes
    volumes:
      - ./tmp/redis:/data
  rcli:
    image: redis:latest
    links:
      - redis
    command: >
      sh -c 'redis-cli -h redis '`

**Comment by shankha-das** [comment]
It was a disk space issue. It's resolved. Thanks for the reply.
