### ISSUE TITLE
create releases on GitHub

### ISSUE THREAD

**Issue by collinbarrett** [docker-library/mariadb#317]
Would it be possible to configure GitHub releases when a new image tag is created? I would love to be able to get notified via a [GitHub release-only watch subscription](https://docs.github.com/en/enterprise/2.20/user/github/receiving-notifications-about-activity-on-github/watching-and-unwatching-releases-for-a-repository) when a new mariadb image is released.

**Comment by yosifkit** [comment]
That would unfortunately not be that meaningful here.

1. Dockerfile changes, but Docker Hub has not: The `Dockerfile` being updated with a new version and it being available to `docker pull` are only a partially automated process (on purpose, human review is an important part of the process). See also https://github.com/docker-library/faq/#an-images-source-changed-in-git-now-what.

2. Dockerfile hasn't changed, but Docker Hub image does: While the `10.5.4` image on Docker Hub is currently built by [this Dockerfile](https://github.com/docker-library/mariadb/blob/8ec795570021bdcf933a60d13b4631912634a5cc/10.5/Dockerfile), it will be rebuilt if `ubuntu:focal` gets updated.  This ensures that any packages installed in `ubuntu:focal` or in the layers of the `mariadb` image are the most up to date to include bug/security fixes.  The `ubuntu` images are rebuilt at least monthly.

If you just want MariaDB releases, I would suggest following their repo (https://github.com/MariaDB/server), the automated `update.sh` script gets their releases as fast as we see them. There will be some delay since we install from their apt repos, so we have to wait until it is available there.
