### ISSUE TITLE
Enable ARMv7 support

### ISSUE THREAD

**Issue by awehrfritz** [docker-library/mariadb#328]
When deploying the mariadb image on a ARMv7 SOC (running Armbian), I get the following error:
```
ERROR: no matching manifest for linux/arm/v7 in the manifest list entries
```

I suppose that's because ARMv7 isn't among the supported architectures. Would it be possible to provide support for this?

**Comment by tianon** [comment]
See #125, #204, especially: :disappointed:

> We can only build for architectures that MariaDB supports and provides binaries for, which is the reason for our current supported architectures list.

**Comment by awehrfritz** [comment]
OK, thanks for the heads up.

**Comment by soletan** [comment]
If you happen to stumble over this issue and prefer having any version of MariaDB e.g. with Docker on a Raspberry Pi, just stick to the version that comes included with Ubuntu focal which is used here (though debian:latest comes with a more recent version). Proceed like this **on your RPi**:

1. Check version avalable in container: 
    * `docker run -it --rm ubuntu:focal`
    * `apt update`
    * `apt-cache madison mariadb-server`
    This will list versions available in Ubuntu focal containers, e.g. **1:10.3.34-0ubuntu0.20.04.1**
2. Leave that container, grab a copy of this repo's subfolder matching discovered minor version, e.g. **10.3** in given example. 
3. Adjust Dockerfile of grabbed folder and replace version named there (somewhere around line 85) with the one listed by apt-cache.
4. Now build the mariadb container locally yourself, by running this from within that grabbed folder: `docker build -t mariadb .`.

You might be able to do the same based on debian image which currently comes with 10.5. But remember to fix at least the FROM statement at the beginning of Dockerfile, too. Maybe, the Dockerfile is too specific and thus needs additional revisions, though. Haven't tested that myself ...

**Comment by grooverdan** [comment]
Note next release of [10.8+ will be ubuntu:jammy](https://github.com/MariaDB/mariadb-docker/blob/next/10.8/Dockerfile) which has [MariaDB-10.6](https://launchpad.net/ubuntu/+source/mariadb-10.6) which seems to be supporting the armhf name of arm32v7.

Because all the repo and version are build args something like below might work on the actual hardware (my qemu setup wasn't cooperating with arm32v7). I've reused the default ubuntu ports repository in the build example below (from current `next` branch):

```
 buildah bud --tag m106 --build-arg MARIADB_MAJOR=10.6 --build-arg MARIADB_VERSION=1:10.6.7-3 --build-arg REPOSITORY="http://ports.ubuntu.com/ubuntu-ports/ jammy main"  10.8
 ```
 
 Note per the [FAQ](https://github.com/MariaDB/mariadb-docker#id-like-the-mariadb-on-architecture-x), that there is no armv7 tested by MariaDB developers before release, only the [very thin (994 basic tests out of thousands) set of tests in the ubuntu package build log](https://launchpad.net/ubuntu/+source/mariadb-10.6/1:10.6.7-3/+build/23488407).
