### ISSUE TITLE
No debian-sys-maint user in DB

### ISSUE THREAD

**Issue by m-radzikowski** [docker-library/mariadb#51]
Hi,
I'm new to Docker and I'm configuring MariaDB container. I've noticed that:
- in `/etc/mysql/debian.cnf` password for `debian-sys-maint` is always the same,
- there is no `debian-sys-maint` user in DB, and `service mysql status` gives this result:

```
/usr/bin/mysqladmin: connect to server at 'localhost' failed
error: 'Access denied for user 'debian-sys-maint'@'localhost' (using password: YES)'
```

I don't know, maybe it doesn't matter in Docker environment?

**Edit:** image mariadb:10.1, Docker version 1.10.3 build 20f81dd

**Comment by yosifkit** [comment]
Yeah, we don't use the [default database](https://github.com/docker-library/mariadb/blob/master/10.1/Dockerfile#L36) that is created on install or the init scripts so the `debian.cnf` file doesn't apply.  The sql root password is set on start on the container via an environment variable.  As for `service status`, the container does not run its own init system, so that wouldn't work.  I assume you did a `docker exec -it my-container bash` to see it, so `ps aux` should work.

**Comment by m-radzikowski** [comment]
Ah, ok. Thanks for the info - if this doesn't have negative impact it's fine for me.
