### ISSUE TITLE
Entrypoint - can't execute anything as root

### ISSUE THREAD

**Issue by mrsinham** [docker-library/mariadb#64]
Hello,

Since the commit https://github.com/docker-library/mariadb/pull/59/commits/cc686f56875aa84d135bb89de6ca50385211bdab and the use of gosu to launch the main mariadb entrypoint, we can't launch anything as root (all sh are now executed as "mysql" by default or another user). This change has broken a lots of things in our dev container because we need data from host and -v flag mount those data as root.

Can you look at this please ? Or give us a workaround ?

Thank you.

**Comment by yosifkit** [comment]
The rationale behind the change was to improve the container by dropping root permissions as soon as we were done with it.  In many cases a user can run the container without it ever running as root. This was especially useful for users of boot2docker/docker-machine where the `chown` would fail on the virtualbox shared folder.

A few ideas for workarounds:

 - don't mount the needed directories as root; instead chown the mounted folders to user X and run mariadb as specified user: `docker run --user X  -v... mariadb`
 - start mariadb with bind mount for database (`/var/lib/mysql`) so that database files will be initialized. stop and remove container. start new container with same mount and with extra mounts for your other files, use your own entrypoint script  (`--entrypoint`) to mimic part of the orginal entrypoint to run your other scripts and then start finish by starting `mysqld` like the original script does
  - could also make use of `--volumes-from` to get the initialized database from your first container to the next
 - could just copy and edit the entrypoint and mount it with your extra scripts and run the container with your customized `docker-entrypoint.sh`

**Comment by mrsinham** [comment]
Hello,

Thanks for the explanation but it seems to be complicated. For the first proposal we need to chown files on the host (and we dont want). The second one is very complicated and we need a solution ouf of the box. The final one is not very cool because we lose all the changes you apply.

Another proposal is to imagine a path where  scripts are executed before gosu as mysql ? for all the mysql commands, we dont need more.

Most of the scripts are going to /docker-entrypoint-initdb.d/* and the root ones on IE /docker-entrypoint-initdb.d.prelaunch/* ?

**Comment by yosifkit** [comment]
Closing old issue.
