### ISSUE TITLE
How to include snappy compression?

### ISSUE THREAD

**Issue by lookingcloudy** [docker-library/mariadb#80]
I'd love to use snappy compression with these images, but there is a lot going on with the official dockerfile.  Is there a version of the dockerfile that might include other compression algorithms?  If not, can you offer some pointers?

**Comment by yosifkit** [comment]
We just use the apt repo provided by MariaDB, so I was hoping that just installing `libsnappy1` would just work.

```Dockerfile
FROM mariadb:10.1
RUN apt-get update && apt-get install -y libsnappy1 && rm -rf /var/lib/apt/lists/*
CMD ["mysqld", "--innodb-compression-algorithm=snappy"]
```

And eventually the error I get is:
```console
2016-09-12 17:52:33 140314025387968 [ERROR] InnoDB: innodb_compression_algorithm = 6 unsupported.
InnoDB: libsnappy is not installed. 
```

I tried all of the compression algorithms from [this page](https://mariadb.com/kb/en/mariadb/compression/) and none of them worked, even after I installed their libs. I think that in order to use them you have to compile your own (or use a distribution that compiles in the support):
> Because all of these compression methods are not available by default on all distributions and MariaDB server does not bundle them, you may need to download the desired compression method package from the above links, install the package and finally recompile MariaDB server from the source distribution

**Comment by tanji** [comment]
Yes, that's unfortunately true. Since MariaDB is pretty much self-contained, we want to avoid reliance on external libraries as much as possible. However if you're interested in testing alternative compression methods, you could build a MariaDB image from Arch Linux, because the MariaDB 10.1 Arch Linux package includes support for LZO, LZMA and LZ4 as well, although Snappy seems to have been left aside.

**Comment by yosifkit** [comment]
Closing old issue.
