### ISSUE TITLE
10.1.3 Image Broken

### ISSUE THREAD

**Issue by JoelBondurant** [docker-library/mariadb#9]
Basic high school level QA isn't being done on MariaDB's Docker images, and the 10.1.3 image is a non-functional release.

**Comment by Moghedrin** [comment]
Undoubtedly, you have checked the [supported versions of MariaDB](https://registry.hub.docker.com/_/mariadb/) before opening this issue, as that would be "basic high school level" research into the problem. As you have, no doubt, simply forgotten, the 10.1 series is a [beta/dev release](https://mariadb.com/kb/en/mariadb/what-is-mariadb-101/), which is why it is no longer on the list of supported versions (#6).

**Comment by majormoses** [comment]
@Moghedrin +1 for the proper response...

**Comment by JoelBondurant** [comment]
Note to self, MariaDB dev releases are non-functional.
